export type Recipe = {
  id: string;
  name: string;
  image: string;
  description: string;
  stepsCount: number;
  rating: number;
  reviewsCount: number;
  tags: string[];
  cuisines: string[];
  ingredients: string[];
  cookMinutes: number;
  prepMinutes: number;
  totalMinutes: number;
  date: string;
  calories: number;
  fat: number;
  saturatedFat: number;
  cholesterol: number;
  sodium: number;
  carbohydrate: number;
  fiber: number;
  sugar: number;
  protein: number;
  _version_: number;
  _ingredientsFacet: string[];
};
